### ISSUE TITLE
Question: Hardware requirement for Quantum

### ISSUE THREAD

**Issue by whitetiger21022014** [Supernomad/quantum#95]
Dear Quantum team,
I'm new with quantum, so I have some questions with your quantum solution for classification:

- Do we need any special hardware RNG (Random Number Generator), photon generator,... ?
- What is the different between your quantum software defined with another quantum solution use RNG hardware (ex: http://www.idquantique.com)
- And may I use your quantum software solution for my system in production or your software is just for demo
Thanks,

**Comment by Supernomad** [comment]
So there is no need for specialized hardware in order to utilize `quantum`. However is seems like there is a misconception about what this project aims to do. `quantum` does not implement quantum encryption, which is a highly experimental and complex type of cryptography. The encryption the this project offers is based on AES and GCM, which are "standard" cryptographic processes.

The technology referenced in the website included in your question, is far beyond the scope of what this project `quantum` intends to offer and implement. However that is not to say that `quantum` can not offer you completely secure communication over the WAN. Secure communication is exactly what `quantum` offers, and does so while being able to run on standard commodity hardware.

As for using this project in production, it is already being used in a production context. If there is anything we can do to help implement this system in your production environment, do not hesitate to ask!

**Comment by whitetiger21022014** [comment]
Thanks for your reply
